// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MMO.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public enum EntityType : sbyte
{
  Player = 0,
  NPC = 1,
  Object = 2,
};

public enum PacketType : byte
{
  NONE = 0,
  LoginRequest = 1,
  LoginResponse = 2,
  MovementUpdate = 3,
  RegisterRequest = 4,
  RegisterResponse = 5,
  RealmListRequest = 6,
  RealmListResponse = 7,
  JoinRealmRequest = 8,
  CharacterListRequest = 9,
  CharacterListResponse = 10,
  CreateCharacterRequest = 11,
  CreateCharacterResponse = 12,
  SelectCharacterRequest = 13,
  DeleteCharacterRequest = 14,
  DeleteCharacterResponse = 15,
};

public struct Vec3 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Vec3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

  public static Offset<MMO.Protocol.Vec3> CreateVec3(FlatBufferBuilder builder, float X, float Y, float Z) {
    builder.Prep(4, 12);
    builder.PutFloat(Z);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<MMO.Protocol.Vec3>(builder.Offset);
  }
};

public struct LoginRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static LoginRequest GetRootAsLoginRequest(ByteBuffer _bb) { return GetRootAsLoginRequest(_bb, new LoginRequest()); }
  public static LoginRequest GetRootAsLoginRequest(ByteBuffer _bb, LoginRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LoginRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Username { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUsernameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUsernameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUsernameArray() { return __p.__vector_as_array<byte>(4); }
  public string ClientVersion { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetClientVersionBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetClientVersionBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetClientVersionArray() { return __p.__vector_as_array<byte>(6); }
  public string Token { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTokenBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetTokenBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetTokenArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<MMO.Protocol.LoginRequest> CreateLoginRequest(FlatBufferBuilder builder,
      StringOffset usernameOffset = default(StringOffset),
      StringOffset client_versionOffset = default(StringOffset),
      StringOffset tokenOffset = default(StringOffset)) {
    builder.StartTable(3);
    LoginRequest.AddToken(builder, tokenOffset);
    LoginRequest.AddClientVersion(builder, client_versionOffset);
    LoginRequest.AddUsername(builder, usernameOffset);
    return LoginRequest.EndLoginRequest(builder);
  }

  public static void StartLoginRequest(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddUsername(FlatBufferBuilder builder, StringOffset usernameOffset) { builder.AddOffset(0, usernameOffset.Value, 0); }
  public static void AddClientVersion(FlatBufferBuilder builder, StringOffset clientVersionOffset) { builder.AddOffset(1, clientVersionOffset.Value, 0); }
  public static void AddToken(FlatBufferBuilder builder, StringOffset tokenOffset) { builder.AddOffset(2, tokenOffset.Value, 0); }
  public static Offset<MMO.Protocol.LoginRequest> EndLoginRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.LoginRequest>(o);
  }
};

public struct LoginResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static LoginResponse GetRootAsLoginResponse(ByteBuffer _bb) { return GetRootAsLoginResponse(_bb, new LoginResponse()); }
  public static LoginResponse GetRootAsLoginResponse(ByteBuffer _bb, LoginResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LoginResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Success { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string ErrorMessage { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetErrorMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetErrorMessageArray() { return __p.__vector_as_array<byte>(6); }
  public ulong PlayerId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public MMO.Protocol.Vec3? SpawnPos { get { int o = __p.__offset(10); return o != 0 ? (MMO.Protocol.Vec3?)(new MMO.Protocol.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartLoginResponse(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(0, success, false); }
  public static void AddErrorMessage(FlatBufferBuilder builder, StringOffset errorMessageOffset) { builder.AddOffset(1, errorMessageOffset.Value, 0); }
  public static void AddPlayerId(FlatBufferBuilder builder, ulong playerId) { builder.AddUlong(2, playerId, 0); }
  public static void AddSpawnPos(FlatBufferBuilder builder, Offset<MMO.Protocol.Vec3> spawnPosOffset) { builder.AddStruct(3, spawnPosOffset.Value, 0); }
  public static Offset<MMO.Protocol.LoginResponse> EndLoginResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.LoginResponse>(o);
  }
};

public struct RegisterRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static RegisterRequest GetRootAsRegisterRequest(ByteBuffer _bb) { return GetRootAsRegisterRequest(_bb, new RegisterRequest()); }
  public static RegisterRequest GetRootAsRegisterRequest(ByteBuffer _bb, RegisterRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RegisterRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Username { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUsernameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUsernameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUsernameArray() { return __p.__vector_as_array<byte>(4); }
  public string Email { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEmailBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetEmailBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetEmailArray() { return __p.__vector_as_array<byte>(6); }
  public string PasswordHash { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPasswordHashBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetPasswordHashBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetPasswordHashArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<MMO.Protocol.RegisterRequest> CreateRegisterRequest(FlatBufferBuilder builder,
      StringOffset usernameOffset = default(StringOffset),
      StringOffset emailOffset = default(StringOffset),
      StringOffset password_hashOffset = default(StringOffset)) {
    builder.StartTable(3);
    RegisterRequest.AddPasswordHash(builder, password_hashOffset);
    RegisterRequest.AddEmail(builder, emailOffset);
    RegisterRequest.AddUsername(builder, usernameOffset);
    return RegisterRequest.EndRegisterRequest(builder);
  }

  public static void StartRegisterRequest(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddUsername(FlatBufferBuilder builder, StringOffset usernameOffset) { builder.AddOffset(0, usernameOffset.Value, 0); }
  public static void AddEmail(FlatBufferBuilder builder, StringOffset emailOffset) { builder.AddOffset(1, emailOffset.Value, 0); }
  public static void AddPasswordHash(FlatBufferBuilder builder, StringOffset passwordHashOffset) { builder.AddOffset(2, passwordHashOffset.Value, 0); }
  public static Offset<MMO.Protocol.RegisterRequest> EndRegisterRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.RegisterRequest>(o);
  }
};

public struct RegisterResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static RegisterResponse GetRootAsRegisterResponse(ByteBuffer _bb) { return GetRootAsRegisterResponse(_bb, new RegisterResponse()); }
  public static RegisterResponse GetRootAsRegisterResponse(ByteBuffer _bb, RegisterResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RegisterResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Success { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string ErrorMessage { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetErrorMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetErrorMessageArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<MMO.Protocol.RegisterResponse> CreateRegisterResponse(FlatBufferBuilder builder,
      bool success = false,
      StringOffset error_messageOffset = default(StringOffset)) {
    builder.StartTable(2);
    RegisterResponse.AddErrorMessage(builder, error_messageOffset);
    RegisterResponse.AddSuccess(builder, success);
    return RegisterResponse.EndRegisterResponse(builder);
  }

  public static void StartRegisterResponse(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(0, success, false); }
  public static void AddErrorMessage(FlatBufferBuilder builder, StringOffset errorMessageOffset) { builder.AddOffset(1, errorMessageOffset.Value, 0); }
  public static Offset<MMO.Protocol.RegisterResponse> EndRegisterResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.RegisterResponse>(o);
  }
};

public struct RealmInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static RealmInfo GetRootAsRealmInfo(ByteBuffer _bb) { return GetRootAsRealmInfo(_bb, new RealmInfo()); }
  public static RealmInfo GetRootAsRealmInfo(ByteBuffer _bb, RealmInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RealmInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public float Population { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public sbyte Status { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }

  public static Offset<MMO.Protocol.RealmInfo> CreateRealmInfo(FlatBufferBuilder builder,
      uint id = 0,
      StringOffset nameOffset = default(StringOffset),
      float population = 0.0f,
      sbyte status = 0) {
    builder.StartTable(4);
    RealmInfo.AddPopulation(builder, population);
    RealmInfo.AddName(builder, nameOffset);
    RealmInfo.AddId(builder, id);
    RealmInfo.AddStatus(builder, status);
    return RealmInfo.EndRealmInfo(builder);
  }

  public static void StartRealmInfo(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddPopulation(FlatBufferBuilder builder, float population) { builder.AddFloat(2, population, 0.0f); }
  public static void AddStatus(FlatBufferBuilder builder, sbyte status) { builder.AddSbyte(3, status, 0); }
  public static Offset<MMO.Protocol.RealmInfo> EndRealmInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.RealmInfo>(o);
  }
};

public struct RealmListRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static RealmListRequest GetRootAsRealmListRequest(ByteBuffer _bb) { return GetRootAsRealmListRequest(_bb, new RealmListRequest()); }
  public static RealmListRequest GetRootAsRealmListRequest(ByteBuffer _bb, RealmListRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RealmListRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRealmListRequest(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<MMO.Protocol.RealmListRequest> EndRealmListRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.RealmListRequest>(o);
  }
};

public struct RealmListResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static RealmListResponse GetRootAsRealmListResponse(ByteBuffer _bb) { return GetRootAsRealmListResponse(_bb, new RealmListResponse()); }
  public static RealmListResponse GetRootAsRealmListResponse(ByteBuffer _bb, RealmListResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RealmListResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MMO.Protocol.RealmInfo? Realms(int j) { int o = __p.__offset(4); return o != 0 ? (MMO.Protocol.RealmInfo?)(new MMO.Protocol.RealmInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RealmsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<MMO.Protocol.RealmListResponse> CreateRealmListResponse(FlatBufferBuilder builder,
      VectorOffset realmsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    RealmListResponse.AddRealms(builder, realmsOffset);
    return RealmListResponse.EndRealmListResponse(builder);
  }

  public static void StartRealmListResponse(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddRealms(FlatBufferBuilder builder, VectorOffset realmsOffset) { builder.AddOffset(0, realmsOffset.Value, 0); }
  public static VectorOffset CreateRealmsVector(FlatBufferBuilder builder, Offset<MMO.Protocol.RealmInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRealmsVectorBlock(FlatBufferBuilder builder, Offset<MMO.Protocol.RealmInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartRealmsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<MMO.Protocol.RealmListResponse> EndRealmListResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.RealmListResponse>(o);
  }
};

public struct JoinRealmRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static JoinRealmRequest GetRootAsJoinRealmRequest(ByteBuffer _bb) { return GetRootAsJoinRealmRequest(_bb, new JoinRealmRequest()); }
  public static JoinRealmRequest GetRootAsJoinRealmRequest(ByteBuffer _bb, JoinRealmRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinRealmRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint RealmId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<MMO.Protocol.JoinRealmRequest> CreateJoinRealmRequest(FlatBufferBuilder builder,
      uint realm_id = 0) {
    builder.StartTable(1);
    JoinRealmRequest.AddRealmId(builder, realm_id);
    return JoinRealmRequest.EndJoinRealmRequest(builder);
  }

  public static void StartJoinRealmRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddRealmId(FlatBufferBuilder builder, uint realmId) { builder.AddUint(0, realmId, 0); }
  public static Offset<MMO.Protocol.JoinRealmRequest> EndJoinRealmRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.JoinRealmRequest>(o);
  }
};

public struct CharacterInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static CharacterInfo GetRootAsCharacterInfo(ByteBuffer _bb) { return GetRootAsCharacterInfo(_bb, new CharacterInfo()); }
  public static CharacterInfo GetRootAsCharacterInfo(ByteBuffer _bb, CharacterInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public sbyte Race { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
  public sbyte CharacterClass { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
  public uint Level { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<MMO.Protocol.CharacterInfo> CreateCharacterInfo(FlatBufferBuilder builder,
      ulong id = 0,
      StringOffset nameOffset = default(StringOffset),
      sbyte race = 0,
      sbyte character_class = 0,
      uint level = 0) {
    builder.StartTable(5);
    CharacterInfo.AddId(builder, id);
    CharacterInfo.AddLevel(builder, level);
    CharacterInfo.AddName(builder, nameOffset);
    CharacterInfo.AddCharacterClass(builder, character_class);
    CharacterInfo.AddRace(builder, race);
    return CharacterInfo.EndCharacterInfo(builder);
  }

  public static void StartCharacterInfo(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, ulong id) { builder.AddUlong(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddRace(FlatBufferBuilder builder, sbyte race) { builder.AddSbyte(2, race, 0); }
  public static void AddCharacterClass(FlatBufferBuilder builder, sbyte characterClass) { builder.AddSbyte(3, characterClass, 0); }
  public static void AddLevel(FlatBufferBuilder builder, uint level) { builder.AddUint(4, level, 0); }
  public static Offset<MMO.Protocol.CharacterInfo> EndCharacterInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.CharacterInfo>(o);
  }
};

public struct CharacterListRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static CharacterListRequest GetRootAsCharacterListRequest(ByteBuffer _bb) { return GetRootAsCharacterListRequest(_bb, new CharacterListRequest()); }
  public static CharacterListRequest GetRootAsCharacterListRequest(ByteBuffer _bb, CharacterListRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterListRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartCharacterListRequest(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<MMO.Protocol.CharacterListRequest> EndCharacterListRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.CharacterListRequest>(o);
  }
};

public struct CharacterListResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static CharacterListResponse GetRootAsCharacterListResponse(ByteBuffer _bb) { return GetRootAsCharacterListResponse(_bb, new CharacterListResponse()); }
  public static CharacterListResponse GetRootAsCharacterListResponse(ByteBuffer _bb, CharacterListResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterListResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MMO.Protocol.CharacterInfo? Characters(int j) { int o = __p.__offset(4); return o != 0 ? (MMO.Protocol.CharacterInfo?)(new MMO.Protocol.CharacterInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CharactersLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<MMO.Protocol.CharacterListResponse> CreateCharacterListResponse(FlatBufferBuilder builder,
      VectorOffset charactersOffset = default(VectorOffset)) {
    builder.StartTable(1);
    CharacterListResponse.AddCharacters(builder, charactersOffset);
    return CharacterListResponse.EndCharacterListResponse(builder);
  }

  public static void StartCharacterListResponse(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCharacters(FlatBufferBuilder builder, VectorOffset charactersOffset) { builder.AddOffset(0, charactersOffset.Value, 0); }
  public static VectorOffset CreateCharactersVector(FlatBufferBuilder builder, Offset<MMO.Protocol.CharacterInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCharactersVectorBlock(FlatBufferBuilder builder, Offset<MMO.Protocol.CharacterInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartCharactersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<MMO.Protocol.CharacterListResponse> EndCharacterListResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.CharacterListResponse>(o);
  }
};

public struct CreateCharacterRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static CreateCharacterRequest GetRootAsCreateCharacterRequest(ByteBuffer _bb) { return GetRootAsCreateCharacterRequest(_bb, new CreateCharacterRequest()); }
  public static CreateCharacterRequest GetRootAsCreateCharacterRequest(ByteBuffer _bb, CreateCharacterRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CreateCharacterRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public sbyte Race { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
  public sbyte CharacterClass { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }

  public static Offset<MMO.Protocol.CreateCharacterRequest> CreateCreateCharacterRequest(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      sbyte race = 0,
      sbyte character_class = 0) {
    builder.StartTable(3);
    CreateCharacterRequest.AddName(builder, nameOffset);
    CreateCharacterRequest.AddCharacterClass(builder, character_class);
    CreateCharacterRequest.AddRace(builder, race);
    return CreateCharacterRequest.EndCreateCharacterRequest(builder);
  }

  public static void StartCreateCharacterRequest(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddRace(FlatBufferBuilder builder, sbyte race) { builder.AddSbyte(1, race, 0); }
  public static void AddCharacterClass(FlatBufferBuilder builder, sbyte characterClass) { builder.AddSbyte(2, characterClass, 0); }
  public static Offset<MMO.Protocol.CreateCharacterRequest> EndCreateCharacterRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.CreateCharacterRequest>(o);
  }
};

public struct CreateCharacterResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static CreateCharacterResponse GetRootAsCreateCharacterResponse(ByteBuffer _bb) { return GetRootAsCreateCharacterResponse(_bb, new CreateCharacterResponse()); }
  public static CreateCharacterResponse GetRootAsCreateCharacterResponse(ByteBuffer _bb, CreateCharacterResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CreateCharacterResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Success { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string ErrorMessage { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetErrorMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetErrorMessageArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<MMO.Protocol.CreateCharacterResponse> CreateCreateCharacterResponse(FlatBufferBuilder builder,
      bool success = false,
      StringOffset error_messageOffset = default(StringOffset)) {
    builder.StartTable(2);
    CreateCharacterResponse.AddErrorMessage(builder, error_messageOffset);
    CreateCharacterResponse.AddSuccess(builder, success);
    return CreateCharacterResponse.EndCreateCharacterResponse(builder);
  }

  public static void StartCreateCharacterResponse(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(0, success, false); }
  public static void AddErrorMessage(FlatBufferBuilder builder, StringOffset errorMessageOffset) { builder.AddOffset(1, errorMessageOffset.Value, 0); }
  public static Offset<MMO.Protocol.CreateCharacterResponse> EndCreateCharacterResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.CreateCharacterResponse>(o);
  }
};

public struct SelectCharacterRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static SelectCharacterRequest GetRootAsSelectCharacterRequest(ByteBuffer _bb) { return GetRootAsSelectCharacterRequest(_bb, new SelectCharacterRequest()); }
  public static SelectCharacterRequest GetRootAsSelectCharacterRequest(ByteBuffer _bb, SelectCharacterRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SelectCharacterRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<MMO.Protocol.SelectCharacterRequest> CreateSelectCharacterRequest(FlatBufferBuilder builder,
      ulong character_id = 0) {
    builder.StartTable(1);
    SelectCharacterRequest.AddCharacterId(builder, character_id);
    return SelectCharacterRequest.EndSelectCharacterRequest(builder);
  }

  public static void StartSelectCharacterRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCharacterId(FlatBufferBuilder builder, ulong characterId) { builder.AddUlong(0, characterId, 0); }
  public static Offset<MMO.Protocol.SelectCharacterRequest> EndSelectCharacterRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.SelectCharacterRequest>(o);
  }
};

public struct DeleteCharacterRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static DeleteCharacterRequest GetRootAsDeleteCharacterRequest(ByteBuffer _bb) { return GetRootAsDeleteCharacterRequest(_bb, new DeleteCharacterRequest()); }
  public static DeleteCharacterRequest GetRootAsDeleteCharacterRequest(ByteBuffer _bb, DeleteCharacterRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DeleteCharacterRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public string NameConfirmation { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameConfirmationBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameConfirmationBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameConfirmationArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<MMO.Protocol.DeleteCharacterRequest> CreateDeleteCharacterRequest(FlatBufferBuilder builder,
      ulong character_id = 0,
      StringOffset name_confirmationOffset = default(StringOffset)) {
    builder.StartTable(2);
    DeleteCharacterRequest.AddCharacterId(builder, character_id);
    DeleteCharacterRequest.AddNameConfirmation(builder, name_confirmationOffset);
    return DeleteCharacterRequest.EndDeleteCharacterRequest(builder);
  }

  public static void StartDeleteCharacterRequest(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddCharacterId(FlatBufferBuilder builder, ulong characterId) { builder.AddUlong(0, characterId, 0); }
  public static void AddNameConfirmation(FlatBufferBuilder builder, StringOffset nameConfirmationOffset) { builder.AddOffset(1, nameConfirmationOffset.Value, 0); }
  public static Offset<MMO.Protocol.DeleteCharacterRequest> EndDeleteCharacterRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.DeleteCharacterRequest>(o);
  }
};

public struct DeleteCharacterResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static DeleteCharacterResponse GetRootAsDeleteCharacterResponse(ByteBuffer _bb) { return GetRootAsDeleteCharacterResponse(_bb, new DeleteCharacterResponse()); }
  public static DeleteCharacterResponse GetRootAsDeleteCharacterResponse(ByteBuffer _bb, DeleteCharacterResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DeleteCharacterResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Success { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string ErrorMessage { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetErrorMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetErrorMessageArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<MMO.Protocol.DeleteCharacterResponse> CreateDeleteCharacterResponse(FlatBufferBuilder builder,
      bool success = false,
      StringOffset error_messageOffset = default(StringOffset)) {
    builder.StartTable(2);
    DeleteCharacterResponse.AddErrorMessage(builder, error_messageOffset);
    DeleteCharacterResponse.AddSuccess(builder, success);
    return DeleteCharacterResponse.EndDeleteCharacterResponse(builder);
  }

  public static void StartDeleteCharacterResponse(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(0, success, false); }
  public static void AddErrorMessage(FlatBufferBuilder builder, StringOffset errorMessageOffset) { builder.AddOffset(1, errorMessageOffset.Value, 0); }
  public static Offset<MMO.Protocol.DeleteCharacterResponse> EndDeleteCharacterResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.DeleteCharacterResponse>(o);
  }
};

public struct MovementUpdate : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static MovementUpdate GetRootAsMovementUpdate(ByteBuffer _bb) { return GetRootAsMovementUpdate(_bb, new MovementUpdate()); }
  public static MovementUpdate GetRootAsMovementUpdate(ByteBuffer _bb, MovementUpdate obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MovementUpdate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong EntityId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public MMO.Protocol.Vec3? Position { get { int o = __p.__offset(6); return o != 0 ? (MMO.Protocol.Vec3?)(new MMO.Protocol.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float Rotation { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public ulong Timestamp { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static void StartMovementUpdate(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddEntityId(FlatBufferBuilder builder, ulong entityId) { builder.AddUlong(0, entityId, 0); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<MMO.Protocol.Vec3> positionOffset) { builder.AddStruct(1, positionOffset.Value, 0); }
  public static void AddRotation(FlatBufferBuilder builder, float rotation) { builder.AddFloat(2, rotation, 0.0f); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(3, timestamp, 0); }
  public static Offset<MMO.Protocol.MovementUpdate> EndMovementUpdate(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.MovementUpdate>(o);
  }
};

public struct MasterPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { }
  public static MasterPacket GetRootAsMasterPacket(ByteBuffer _bb) { return GetRootAsMasterPacket(_bb, new MasterPacket()); }
  public static MasterPacket GetRootAsMasterPacket(ByteBuffer _bb, MasterPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MasterPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MMO.Protocol.PacketType DataType { get { int o = __p.__offset(4); return o != 0 ? (MMO.Protocol.PacketType)__p.bb.Get(o + __p.bb_pos) : MMO.Protocol.PacketType.NONE; } }
  public TTable? Data<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }

  public static Offset<MMO.Protocol.MasterPacket> CreateMasterPacket(FlatBufferBuilder builder,
      MMO.Protocol.PacketType data_type = MMO.Protocol.PacketType.NONE,
      int dataOffset = 0) {
    builder.StartTable(2);
    MasterPacket.AddData(builder, dataOffset);
    MasterPacket.AddDataType(builder, data_type);
    return MasterPacket.EndMasterPacket(builder);
  }

  public static void StartMasterPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddDataType(FlatBufferBuilder builder, MMO.Protocol.PacketType dataType) { builder.AddByte(0, (byte)dataType, 0); }
  public static void AddData(FlatBufferBuilder builder, int dataOffset) { builder.AddOffset(1, dataOffset, 0); }
  public static Offset<MMO.Protocol.MasterPacket> EndMasterPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MMO.Protocol.MasterPacket>(o);
  }
  public static void FinishMasterPacketBuffer(FlatBufferBuilder builder, Offset<MMO.Protocol.MasterPacket> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMasterPacketBuffer(FlatBufferBuilder builder, Offset<MMO.Protocol.MasterPacket> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
